# Generated by Django 5.2.8 on 2025-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbl_number', models.CharField(max_length=100, verbose_name='رقم البوليصة')),
                ('container_number', models.CharField(max_length=50, verbose_name='رقم الحاوية')),
                ('shipment_type', models.CharField(choices=[('general', 'عامة'), ('food', 'مواد غذائية'), ('chemicals', 'كيماويات'), ('electronics', 'الكترونيات')], max_length=20, verbose_name='نوع الشحنة')),
                ('port', models.CharField(max_length=100, verbose_name='ميناء الوصول')),
                ('arrival_date', models.DateField(verbose_name='تاريخ الوصول')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
            },
        ),
    ]
