# Generated by Django 5.2.8 on 2025-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('port_pickup', 'استلام من الميناء'), ('port_delivery', 'نقل من الميناء'), ('warehouse', 'نقل إلى المستودع'), ('customer_delivery', 'تسليم للعميل')], max_length=30, verbose_name='نوع المهمة')),
                ('driver_name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('task_date', models.DateField(verbose_name='تاريخ المهمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('done', 'منفذة'), ('canceled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments_app.shipment', verbose_name='الشحنة المرتبطة')),
            ],
            options={
                'verbose_name': 'مهمة نقل',
                'verbose_name_plural': 'مهام النقل',
            },
        ),
    ]
