# Generated by Django 5.2.8 on 2025-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('cr_number', models.CharField(max_length=50, verbose_name='رقم السجل التجاري')),
                ('cr_expiry_date', models.DateField(verbose_name='تاريخ انتهاء السجل')),
                ('authorization_number', models.CharField(max_length=50, verbose_name='رقم التفويض')),
                ('authorization_expiry', models.DateField(verbose_name='تاريخ انتهاء التفويض')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
    ]
