# Generated by Django 5.2.8 on 2025-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('arrived', 'وصلت للميناء'), ('documents', 'رفع المستندات'), ('customs', 'جاري التخليص'), ('ready', 'جاهزة للسحب'), ('delivered', 'تم التسليم')], max_length=20, verbose_name='الحالة الحالية')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipments_app.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'عملية تخليص',
                'verbose_name_plural': 'عمليات التخليص',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200, verbose_name='اسم المرحلة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_app.workflow', verbose_name='العملية')),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'مراحل التخليص',
            },
        ),
    ]
