# Generated by Django 5.2.8 on 2025-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('cr_number', models.CharField(max_length=50, verbose_name='رقم السجل التجاري')),
                ('cr_expiry_days', models.IntegerField(default=30, verbose_name='تنبيه انتهاء السجل (يوم)')),
                ('vat_number', models.CharField(max_length=50, verbose_name='الرقم الضريبي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('iban', models.CharField(max_length=30, verbose_name='رقم الآيبان')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
