# Generated by Django 5.2.8 on 2025-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_cr_expiry', models.BooleanField(default=True, verbose_name='تنبيه انتهاء السجل التجاري')),
                ('notify_auth_expiry', models.BooleanField(default=True, verbose_name='تنبيه انتهاء التفويض')),
                ('notify_missing_docs', models.BooleanField(default=True, verbose_name='تنبيه المستندات الناقصة')),
            ],
            options={
                'verbose_name': 'إعدادات التنبيهات',
                'verbose_name_plural': 'إعدادات التنبيهات',
            },
        ),
        migrations.CreateModel(
            name='ShipmentsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_shipment_number', models.PositiveIntegerField(default=1, verbose_name='تسلسل الشحنات')),
                ('enable_label_print', models.BooleanField(default=True, verbose_name='تفعيل طباعة الملصق')),
                ('enable_docs_print', models.BooleanField(default=True, verbose_name='تفعيل طباعة المستندات')),
            ],
            options={
                'verbose_name': 'إعدادات الشحنات',
                'verbose_name_plural': 'إعدادات الشحنات',
            },
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='cr_expiry_days',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.CharField(default=0, max_length=300, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='iban',
            field=models.CharField(max_length=50, verbose_name='رقم الحساب البنكي (IBAN)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='رقم التواصل'),
        ),
    ]
